server:
  listen: ":80"

  timeouts:
    read: 10s
    write: 10s
    idle: 60s

  limits:
    max_header_bytes: 1048576

  tls:
    listen: ":443"
    cert_file: "./certs/fullchain.pem"
    key_file: "./certs/privkey.pem"
    redirect_http: true